AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Simple Infra Project\n"
Parameters:
  Empty:
    Type: String
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: AllowLambdaGlobal
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:*
            - ses:*
            - sns:*
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            Resource: '*'
  Negotations:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${AWS::StackName}-negotiations
      AttributeDefinitions:
      - AttributeName: negotiation_id
        AttributeType: S
      - AttributeName: customer_id
        AttributeType: S
      KeySchema:
      - AttributeName: negotiation_id
        KeyType: HASH
      - AttributeName: customer_id
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
  Tasks:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${AWS::StackName}-tasks
      AttributeDefinitions:
      - AttributeName: task_id
        AttributeType: S
      - AttributeName: negotiation_id
        AttributeType: S
      KeySchema:
      - AttributeName: task_id
        KeyType: HASH
      - AttributeName: negotiation_id
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
  Customers:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${AWS::StackName}-customers
      AttributeDefinitions:
      - AttributeName: customer_id
        AttributeType: S
      KeySchema:
      - AttributeName: customer_id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
  NegotiationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Sub: ${AWS::StackName}-negotiation-topic
  NegotiationTaskTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Sub: ${AWS::StackName}-task-topic
  GiroProposals:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${AWS::StackName}-giro-proposals
      AttributeDefinitions:
      - AttributeName: proposal_id
        AttributeType: S
      - AttributeName: customer_id
        AttributeType: S
      KeySchema:
      - AttributeName: proposal_id
        KeyType: HASH
      - AttributeName: customer_id
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
