AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Simple API Project
Parameters:
  Empty:
    Type: String
  LambdaRole:
    Type: String
Resources:
  API:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: ${AWS::StackName}-api
      StageName: dev
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'GET,OPTIONS,POST,PUT,PATCH,DELETE'"
        AllowHeaders: "'X-Forwarded-For,Access-Control-Allow-Origin,Access-Control-Allow-Credentials,Access-Control-Allow-Methods,Access-Control-Allow-Headers,Origin,Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Requested-With'"
        AllowOrigin: "'*'"
  CustomersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-customers-function
      Runtime: nodejs14.x
      CodeUri: s3://371716203543-artifacts/builds/bdd6f3304801a84ae9402a8b7597dd4c
      Handler: index.lambdaHandler
      Role:
        Ref: LambdaRole
      Layers:
      - Ref: CoreLayer
      Events:
        CustomersFunctionGetAll:
          Type: Api
          Properties:
            Path: /customers
            Method: get
            RestApiId:
              Ref: API
        CustomersFunctionGet:
          Type: Api
          Properties:
            Path: /customers/{customer_id}
            Method: get
            RestApiId:
              Ref: API
        CustomersFunctionPost:
          Type: Api
          Properties:
            Path: /customers
            Method: post
            RestApiId:
              Ref: API
  GiroProposalFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-giro-proposal-function
      Runtime: nodejs14.x
      CodeUri: s3://371716203543-artifacts/builds/f142dbfad027f10900f0dc2570102b57
      Handler: index.lambdaHandler
      Role:
        Ref: LambdaRole
      Layers:
      - Ref: CoreLayer
      Events:
        GiroProposalFunctionAll:
          Type: Api
          Properties:
            Path: /products/giro/proposals
            Method: get
            RestApiId:
              Ref: API
        GiroProposalFunctionGet:
          Type: Api
          Properties:
            Path: /products/giro/proposals/{proposal_id}
            Method: get
            RestApiId:
              Ref: API
        GiroProposalFunctionPost:
          Type: Api
          Properties:
            Path: /products/giro/proposals
            Method: post
            RestApiId:
              Ref: API
  NegotiationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-negotation-function
      Runtime: nodejs14.x
      CodeUri: s3://371716203543-artifacts/builds/5d44a60de868446c02972e3289f994c8
      Handler: index.lambdaHandler
      Role:
        Ref: LambdaRole
      Layers:
      - Ref: CoreLayer
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-2:371716203543:plat-infra-negotiation-topic
        NegotiationFunctionGetAll:
          Type: Api
          Properties:
            Path: /negotiations
            Method: get
            RestApiId:
              Ref: API
        NegotiationFunctionGet:
          Type: Api
          Properties:
            Path: /negotiations/{negotiation_id}
            Method: get
            RestApiId:
              Ref: API
  TaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-task-function
      Runtime: nodejs14.x
      CodeUri: s3://371716203543-artifacts/builds/818fe8f347044d75feed28e2eff1c35c
      Handler: index.lambdaHandler
      Role:
        Ref: LambdaRole
      Layers:
      - Ref: CoreLayer
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-2:371716203543:plat-infra-task-topic
        TaskFunctionGetAll:
          Type: Api
          Properties:
            Path: /tasks
            Method: get
            RestApiId:
              Ref: API
        TaskFunctionGet:
          Type: Api
          Properties:
            Path: /tasks/{task_id}
            Method: get
            RestApiId:
              Ref: API
  CoreLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${AWS::StackName}-api
      Description: Dependencies for API
      ContentUri: s3://371716203543-artifacts/builds/8737d7b71552f303bd15ee38e08fa0c8
      CompatibleRuntimes:
      - nodejs12.x
      LicenseInfo: MIT
  CustomersFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
        - /
        - - /aws/lambda
          - Ref: CustomersFunction
      RetentionInDays: 3
  GiroProposalFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
        - /
        - - /aws/lambda
          - Ref: GiroProposalFunction
      RetentionInDays: 3
  NegotiationFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
        - /
        - - /aws/lambda
          - Ref: NegotiationFunction
      RetentionInDays: 3
  TaskFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
        - /
        - - /aws/lambda
          - Ref: TaskFunction
      RetentionInDays: 3
